sudo: false

language: lisp

env:
  matrix:
    # - LISP=abcl
    - LISP=sbcl
    # - LISP=sbcl32
    - LISP=ccl
    # - LISP=ccl32
    # - LISP=clisp
    # - LISP=clisp32
    # - LISP=cmucl
    # - LISP=ecl

## Lets get clisp to work properly, so fail the build
## if clisp build fails.
#matrix:
# allow_failures:
#   - env: LISP=clisp

install:
  - apt-get install texinfo sbcl
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw2.github.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - cl-launch -i '(ql:quickload "clx")' -i '(ql:quickload "cl-ppcre")'

before_script:
  - ./autogen.sh
  - ./configure

script:
  - make
  #- make test
